#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json.Nodes;

namespace sage_engine;

// The other half of the TrenchBroom bridge (docs/design/15 §3, TODO F16).
//
// An `.fgd` is what tells an editor which entities a game has. Writing one by hand means keeping a
// second list of every prefab, which goes stale the first time somebody adds one — so it is generated
// from the records the game already has, and regenerating it is a console command.
//
// **Every key in here is a key the importer reads.** That rule is worth stating because the temptation
// is the opposite: the engine could reflect over component fields and emit a key for each, and a mapper
// would fill them in and nothing would happen, because `MapLoader` applies `origin`, `angle` and
// `targetname` and leaves the rest on the parsed entity. Per-component keys wait for the declared
// metadata the source generator brings (09 §3.2); until then an FGD that promises less is worth more.
public static class FgdExport
{
    public static void RegisterCommand(Engine engine)
    {
        engine.CVars.RegisterCommand("fgd_export", CVarFlags.DevOnly,
            "fgd_export [file]: write a TrenchBroom .fgd for this game's prefabs (default user://sage.fgd).", a =>
        {
            string path = a.Count > 0 ? a[0] : Path.Combine(UserPaths.Root, "sage.fgd");
            try
            {
                File.WriteAllText(path, Build(engine));
                Log.Info(LogCat.Console, $"wrote {path}");
            }
            catch (IOException ex)
            {
                Log.Warn(LogCat.Console, $"fgd_export: {ex.Message}");
            }
        });
    }

    // The file's text. Built as a string rather than written straight out so a test can read it.
    public static string Build(Engine engine, float scale = MapSpace.DefaultScale)
    {
        float unitsPerMetre = scale > 0f ? 1f / scale : 32f;
        var text = new StringBuilder();

        text.AppendLine("// TrenchBroom entity definitions for sage-engine.");
        text.AppendLine("//");
        text.AppendLine("// Generated by `fgd_export` from this game's prefab records — do not edit by hand, it is");
        text.AppendLine("// rewritten whenever the prefabs change. A classname here is a prefab id: what the entity");
        text.AppendLine("// actually is lives in the record, so a game can change it without touching a level.");
        text.AppendLine($"// {unitsPerMetre:0.#} map units to the metre (docs/design/15 §3).");
        text.AppendLine();

        text.AppendLine("@baseclass = Named [");
        text.AppendLine("    targetname(target_source) : \"Name\" : : \"The entity's name in the world, for anything that looks it up.\"");
        text.AppendLine("]");
        text.AppendLine();
        text.AppendLine("@baseclass = Angled [");
        text.AppendLine("    angle(integer) : \"Yaw\" : 0 : \"Degrees counter-clockwise from east, as in Quake.\"");
        text.AppendLine("]");
        text.AppendLine();
        text.AppendLine("@SolidClass = worldspawn : \"The level itself: every brush in it becomes geometry and collision.\" []");
        text.AppendLine();

        // Entity I/O, as a comment rather than as FGD `output` lines: TrenchBroom is a Quake-family
        // editor and does not parse Source's output syntax, but it does let a mapper type any key on any
        // entity — which is exactly what a wire is. So the file says what to type.
        text.AppendLine("// ---- Wiring (entity I/O, docs/design/04 §3.4) --------------------------------");
        text.AppendLine("//");
        text.AppendLine("// Add a key named after an output, with a value of: target,input[,parameter,delay,times]");
        text.AppendLine("//   \"OnUse\"  \"hut_door,Open\"           using this opens the door named hut_door");
        text.AppendLine("//   \"OnStartTouch\" \"!self,Say,Hello,0,1\"  once, when something walks in");
        text.AppendLine("//");
        text.AppendLine("// Targets may be a targetname, or !self / !activator / !caller.");
        text.AppendLine("// Outputs the engine fires: OnUse (something used it), OnStartTouch / OnEndTouch (a");
        text.AppendLine("// trigger volume: put \"trigger\" \"1\" on a brush entity), OnFullyOpen / OnFullyClosed (a mover).");

        var inputs = new List<string>(engine.Inputs.Names);
        inputs.Sort(StringComparer.OrdinalIgnoreCase);
        text.AppendLine($"// Inputs this game has: {string.Join(", ", inputs)}.");
        text.AppendLine();

        var prefabs = new List<RecordId>(engine.Records.Ids("prefab"));
        prefabs.Sort((a, b) => string.CompareOrdinal(a.ToString(), b.ToString()));

        foreach (var id in prefabs)
        {
            if (!engine.Records.TryGet(id, out PrefabRecord prefab)) continue;

            var (min, max) = SizeOf(prefab, unitsPerMetre);
            string description = Describe(id, prefab);

            text.AppendLine($"@PointClass base(Named, Angled) size({min}, {max}) = {id.Name} : \"{Escape(description)}\" []");
        }

        text.AppendLine();
        text.AppendLine($"// {prefabs.Count} prefab(s).");
        return text.ToString();
    }

    // The box TrenchBroom draws for the entity. A prefab that says how big it is in a `Collider` gets
    // that; anything else gets a small box, because an entity you cannot see is an entity you cannot
    // place. Note the units: the editor thinks in map units and the record is in metres.
    private static (string Min, string Max) SizeOf(PrefabRecord prefab, float unitsPerMetre)
    {
        float width = 0.5f, height = 1f;

        // A prefab says how big it is in its `body` part far more often than in a `Collider` component,
        // because that is how prefabs are written (`"body": { "size": [0.6, 1.8, 0.6] }` or a capsule's
        // radius and height). Both are read; without the part, every entity in TrenchBroom was the same
        // anonymous cube.
        var collider = prefab.Components?["Collider"] as JsonObject ?? prefab.Parts?["body"] as JsonObject;
        if (collider != null)
        {
            if (collider["size"] is JsonArray size && size.Count >= 3)
            {
                width = Read(size[0], width);
                height = Read(size[1], height);
            }
            else if (collider["radius"] is { } radius)
            {
                width = Read(radius, width) * 2f;
                height = Read(collider["height"], height);
            }
        }

        float halfWidth = width * 0.5f * unitsPerMetre;
        float tall = height * unitsPerMetre;
        var culture = CultureInfo.InvariantCulture;

        // Standing on its feet: the box sits on the entity's origin, which is where a `.map` puts it and
        // where the engine spawns it.
        return ($"{(-halfWidth).ToString("0", culture)} {(-halfWidth).ToString("0", culture)} 0",
                $"{halfWidth.ToString("0", culture)} {halfWidth.ToString("0", culture)} {tall.ToString("0", culture)}");
    }

    private static float Read(JsonNode? node, float fallback) =>
        node != null && float.TryParse(node.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out float v)
            ? v : fallback;

    // What the mapper sees in the entity browser: the prefab's own name, and what it is made of — which
    // is the most useful thing the engine can honestly say about it today.
    private static string Describe(RecordId id, PrefabRecord prefab)
    {
        var parts = new List<string>();
        if (prefab.Components != null)
            foreach (var pair in prefab.Components) parts.Add(pair.Key);
        if (prefab.Parts != null)
            foreach (var pair in prefab.Parts) parts.Add(pair.Key);

        string name = string.IsNullOrEmpty(prefab.Name) ? id.Name : prefab.Name;
        return parts.Count == 0 ? $"{name} ({id})" : $"{name} ({id}): {string.Join(", ", parts)}";
    }

    private static string Escape(string text) => text.Replace("\"", "'");
}
