# -*- coding: utf-8 -*-
"""The Sandbox's brush level and the textures on it (docs/design/15 §3, TODO F16).

Two things come out of here, for the same reason the sprites and the bunny do: the repository ships no
art it did not make.

  - `content/maps/hut.map` — a one-room hut with a doorway, in TrenchBroom's standard format. It is a
    text file and a person can open it in TrenchBroom and push the walls around; this script exists so
    the *first* one did not have to be placed by hand, and so the geometry that the tests and the
    screenshots rely on can be regenerated exactly.
  - `content/textures/hut_*.png` — 64×64 tiling textures, which is the size `MapSpace` assumes, so a
    face scaled 1 in the editor shows one tile per 64 units.

Quake units: 32 to the metre. The hut is eight metres square inside and four metres tall.

Run:  python games/Sandbox/tools/make_hut.py
"""
import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(HERE, '..', 'content')

# ---------------------------------------------------------------- the map

# A brush is six planes, and each plane is three points written clockwise seen from outside. These two
# corners are the canonical Quake form: the three lowest faces hang off the minimum corner and the three
# highest off the maximum, which is exactly what every Quake tool has emitted since 1996.
def box(lo, hi, texture, scale=1):
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    faces = [
        ((x0, y0, z0), (x0, y0 + 1, z0), (x0, y0, z0 + 1)),      # -X
        ((x0, y0, z0), (x0, y0, z0 + 1), (x0 + 1, y0, z0)),      # -Y
        ((x0, y0, z0), (x0 + 1, y0, z0), (x0, y0 + 1, z0)),      # -Z (floor of the box)
        ((x1, y1, z1), (x1, y1 + 1, z1), (x1 + 1, y1, z1)),      # +Z (ceiling of the box)
        ((x1, y1, z1), (x1 + 1, y1, z1), (x1, y1, z1 + 1)),      # +Y
        ((x1, y1, z1), (x1, y1, z1 + 1), (x1, y1 + 1, z1)),      # +X
    ]
    lines = ['{']
    for p1, p2, p3 in faces:
        lines.append('( %d %d %d ) ( %d %d %d ) ( %d %d %d ) %s 0 0 0 %d %d'
                     % (p1 + p2 + p3 + (texture, scale, scale)))
    lines.append('}')
    return lines


def hut():
    """A room you can walk into: floor, four walls, a doorway in the south one, and a roof."""
    inner, wall, height, thick = 128, 16, 128, 16      # inner half-width, wall thickness, wall height
    out = inner + wall                                 # outer half-width
    door, lintel = 32, 96                              # doorway half-width and height

    brushes = []
    brushes += box((-out, -out, -thick), (out, out, 0), 'floor', 1)             # floor slab
    brushes += box((-out, -out, height), (out, out, height + thick), 'roof', 1)  # roof slab
    brushes += box((-out, inner, 0), (out, out, height), 'wall', 1)             # north wall
    brushes += box((-out, -out, 0), (-inner, inner, height), 'wall', 1)         # west wall
    brushes += box((inner, -out, 0), (out, inner, height), 'wall', 1)           # east wall

    # The south wall, in three pieces, which is how a doorway is made: two jambs and the lintel over it.
    brushes += box((-out, -out, 0), (-door, -inner, height), 'wall', 1)
    brushes += box((door, -out, 0), (out, -inner, height), 'wall', 1)
    brushes += box((-door, -out, lintel), (door, -inner, height), 'wall', 1)
    return brushes


def write_map(path):
    lines = ['// Generated by games/Sandbox/tools/make_hut.py - TrenchBroom can open and edit this.',
             '// Game: Generic   Format: Standard',
             '{',
             '"classname" "worldspawn"',
             '"message" "The hut"']
    lines += hut()
    lines.append('}')

    # Things standing in it. `classname` is a prefab id, so `watcher` is the Sandbox's watcher; the
    # engine spawns whatever it has a prefab for and says so about the rest.
    # Two lamps under the roof, which is what makes the inside of a hut look like the inside of a hut
    # rather than a dark grey box: 96 units up is just under the lintel, and 64 either side of the middle
    # puts one over each half of the room (F2's point lights).
    for classname, origin, angle in [('info_player_start', (0, -64, 8), 90),
                                     ('watcher', (64, 64, 8), 225),
                                     ('tree', (-220, 200, 8), 0),
                                     ('light', (-64, 32, 96), 0),
                                     ('light', (64, 32, 96), 0)]:
        lines += ['{', '"classname" "%s"' % classname,
                  '"origin" "%d %d %d"' % origin, '"angle" "%d"' % angle, '}']

    # The door: a *solid entity*, which is brushes with a classname on them (F17). `door` is a prefab,
    # so what the door does - slide up three metres and shut itself again - lives in the prefab, and the
    # map only says where it is and what using it does.
    #
    # `OnUse` is written the way Hammer writes an output: target, input, parameter, delay, times.
    # `!self` is the entity that fired it, so the door opens itself; a lever across the room would say
    # `hut_door,Open` instead.
    lines += ['{', '"classname" "door"', '"targetname" "hut_door"',
              '"OnUse" "!self,Open"',
              '"OnFullyOpen" "!self,Say,The door swings open.,0,1"']
    lines += box((-32, -144, 0), (32, -128, 96), 'door', 1)
    lines.append('}')

    # A trigger volume just inside the doorway: brushes with `"trigger" "1"` are something you walk into
    # rather than against, and the engine turns the physics overlap into `OnStartTouch` (F17). Once only,
    # so it greets you rather than nagging.
    lines += ['{', '"classname" "trigger"', '"targetname" "hut_greeting"', '"trigger" "1"',
              '"OnStartTouch" "!self,Say,Somebody has been living here.,0,1"']
    lines += box((-48, -120, 0), (48, -72, 96), 'door', 1)
    lines.append('}')

    text = '\n'.join(lines) + '\n'
    open(path, 'w', newline='\n').write(text)
    brushes = text.count('\n{\n(') + text.count('{\n(')
    print('%-14s %5d bytes, %d brushes' % (os.path.basename(path), len(text), sum(1 for l in lines if l == '{') - 1 - 3))


# ---------------------------------------------------------------- the textures

def write_png(path, width, height, pixels):
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        for x in range(width):
            raw += bytes(pixels[y * width + x])

    def chunk(tag, data):
        body = tag + data
        return struct.pack('>I', len(data)) + body + struct.pack('>I', zlib.crc32(body) & 0xFFFFFFFF)

    png = (b'\x89PNG\r\n\x1a\n'
           + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 6, 0, 0, 0))
           + chunk(b'IDAT', zlib.compress(bytes(raw), 9))
           + chunk(b'IEND', b''))
    open(path, 'wb').write(png)
    print('%-14s %dx%d  %5d bytes' % (os.path.basename(path), width, height, len(png)))


def noise(x, y, seed):
    """A cheap repeatable hash, so the same texture comes out of every run."""
    n = (x * 73856093) ^ (y * 19349663) ^ (seed * 83492791)
    n = (n ^ (n >> 13)) * 1274126177
    return ((n ^ (n >> 16)) & 0xFF) / 255.0


SIZE = 64


def stone_wall():
    """Courses of blocks, offset every other row, with mortar between them."""
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            course = y // 16
            offset = 16 if course % 2 else 0
            mortar = (y % 16) < 2 or ((x + offset) % 32) < 2
            shade = 0.55 + 0.25 * noise(x // 4, y // 4, 1)
            if mortar:
                shade *= 0.6
            grey = int(150 * shade) + 40
            pixels.append((grey, grey - 4, grey - 10, 255))
    return pixels


def plank_floor():
    """Boards running east-west, each with its own grain."""
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            board = y // 16
            edge = (y % 16) < 1
            grain = 0.75 + 0.2 * noise(x // 2, board, 7)
            if edge:
                grain *= 0.55
            pixels.append((int(130 * grain) + 30, int(95 * grain) + 20, int(55 * grain) + 12, 255))
    return pixels


def oak_door():
    """Vertical boards with two iron bands across them, so its travel is easy to see."""
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            plank = x // 8
            gap = (x % 8) == 0
            band = 12 <= y <= 15 or 48 <= y <= 51
            shade = 0.6 + 0.3 * noise(plank, y // 3, 23)
            if gap:
                shade *= 0.5
            if band:
                grey = int(90 * (0.8 + 0.2 * noise(x, y, 5)))
                pixels.append((grey, grey, grey + 6, 255))
            else:
                pixels.append((int(120 * shade) + 35, int(80 * shade) + 22, int(40 * shade) + 12, 255))
    return pixels


def thatch_roof():
    """Straw laid in rows: no structure to it beyond the direction it lies in."""
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            row = y // 8
            straw = 0.6 + 0.35 * noise(x, row, 13)
            if (y % 8) == 0:
                straw *= 0.7
            pixels.append((int(150 * straw) + 40, int(125 * straw) + 30, int(60 * straw) + 15, 255))
    return pixels


def main():
    maps = os.path.join(CONTENT, 'maps')
    textures = os.path.join(CONTENT, 'textures')
    for folder in (maps, textures):
        if not os.path.isdir(folder):
            os.makedirs(folder)

    write_map(os.path.join(maps, 'hut.map'))
    write_png(os.path.join(textures, 'hut_wall.png'), SIZE, SIZE, stone_wall())
    write_png(os.path.join(textures, 'hut_floor.png'), SIZE, SIZE, plank_floor())
    write_png(os.path.join(textures, 'hut_roof.png'), SIZE, SIZE, thatch_roof())
    write_png(os.path.join(textures, 'hut_door.png'), SIZE, SIZE, oak_door())


if __name__ == '__main__':
    main()
