# -*- coding: utf-8 -*-
"""The Sandbox's crypt: an interior behind a door on the hut's hill (engine issue 4g-7).

`content/maps/crypt.map`, in TrenchBroom's standard format like the hut (make_hut.py, whose `box` this
uses): a corridor running north from the way out into a burial chamber. It is the scene `sandbox:crypt`,
which is `"space": "interior"` - no sun, no sky, no terrain - so what lights it is what is in it: three
torches (the `crypt_torch` prefab, a point light that is always on) and the scene's dim ambient.

What a load door needs from a map is a *name*: the way in is the point `crypt_in` (a `targetname` on an
entity with no prefab, which the engine leaves unspawned and travel still finds), and the way out is the
`crypt_exit` prefab (named `crypt_exit` too), a door whose `load_door` leads back to `crypt_steps` on the hill.

Quake units, 32 to the metre: the corridor is three metres wide and ten long, the chamber twelve square,
both four metres high.

Run:  python games/Sandbox/tools/make_crypt.py
"""
import os

from make_hut import box, CONTENT


def crypt():
    """A corridor (south) opening into a chamber (north), floored and roofed."""
    t, h = 16, 128                     # wall thickness, height
    cw, cy0 = 48, -320                 # corridor half-width, its south end
    rw, ry1 = 192, 384                 # chamber half-width, its north end

    b = []
    b += box((-rw - t, cy0 - t, -t), (rw + t, ry1 + t, 0), 'floor', 1)        # floor slab under both
    b += box((-rw - t, cy0 - t, h), (rw + t, ry1 + t, h + t), 'wall', 1)      # ceiling over both
    # The corridor: two walls and its end, where the way out is.
    b += box((-cw - t, cy0 - t, 0), (-cw, 0, h), 'wall', 1)
    b += box((cw, cy0 - t, 0), (cw + t, 0, h), 'wall', 1)
    b += box((-cw, cy0 - t, 0), (cw, cy0, h), 'wall', 1)
    # The chamber: its south wall either side of the corridor's mouth, then west, east and north.
    b += box((-rw - t, -t, 0), (-cw - t, 0, h), 'wall', 1)
    b += box((cw + t, -t, 0), (rw + t, 0, h), 'wall', 1)
    b += box((-rw - t, 0, 0), (-rw, ry1, h), 'wall', 1)
    b += box((rw, 0, 0), (rw + t, ry1, h), 'wall', 1)
    b += box((-rw - t, ry1, 0), (rw + t, ry1 + t, h), 'wall', 1)
    # A plinth in the middle of the chamber, for something to be buried in.
    b += box((-48, 160, 0), (48, 256, 32), 'wall', 1)
    return b


def write_map(path):
    lines = ['// Generated by games/Sandbox/tools/make_crypt.py - TrenchBroom can open and edit this.',
             '// Game: Generic   Format: Standard',
             '{',
             '"classname" "worldspawn"',
             '"message" "The crypt"']
    lines += crypt()
    lines.append('}')

    # The way in: where a load door's `"entry": "crypt_in"` puts the player, facing north up the corridor.
    lines += ['{', '"classname" "info_target"', '"targetname" "crypt_in"',
              '"origin" "0 -256 8"', '"angle" "90"', '}']

    # The way out, at the corridor's south end: named, so `ent_fire crypt_exit Travel` finds it too.
    lines += ['{', '"classname" "crypt_exit"', '"targetname" "crypt_exit"',
              '"origin" "0 -304 38"', '"angle" "90"', '}']

    # The light: torches in the corridor and the chamber, and a crate to see it on.
    for classname, origin, angle in [('crypt_torch', (0, -160, 96), 0),
                                     ('crypt_torch', (-128, 96, 96), 0),
                                     ('crypt_torch', (128, 320, 96), 0),
                                     ('crate', (128, 64, 40), 0)]:
        lines += ['{', '"classname" "%s"' % classname,
                  '"origin" "%d %d %d"' % origin, '"angle" "%d"' % angle, '}']

    text = '\n'.join(lines) + '\n'
    open(path, 'w', newline='\n').write(text)
    print('%-14s %5d bytes' % (os.path.basename(path), len(text)))


def main():
    maps = os.path.join(CONTENT, 'maps')
    if not os.path.isdir(maps):
        os.makedirs(maps)
    write_map(os.path.join(maps, 'crypt.map'))


if __name__ == '__main__':
    main()
