#nullable enable
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Sage.Client;

// The engine's own font (docs/design/13 §3, TODO R12).
//
// **A grid of glyphs in one texture, and nothing else.** No metrics file, no kerning table, no content
// pipeline: a character's cell is `code - 32`, so where a glyph lives is arithmetic and there is nothing
// that can fall out of step with the atlas. The atlas itself is generated by
// `engine_content/tools/make_font.py`, which is where the letters are actually drawn.
//
// This is what replaced `SpriteFont`, and with it the last thing MGCB was for. The engine now ships no
// font it did not draw, and builds no content at build time except shaders.
public sealed class BitmapFont
{
    // Must match `make_font.py`: an 8×8 cell, a 5×7 glyph inside it, sixteen to a row, starting at
    // ASCII 32. The tool prints the atlas it made; these four numbers are the contract between them.
    public const int Cell = 8;
    public const int GlyphWidth = 5;
    public const int GlyphHeight = 7;
    public const int Columns = 16;
    private const int FirstCode = 32;

    // Past the printable ASCII the tool appends the few characters the engine's own hint lines use.
    private static readonly char[] Extras = { '↑', '↓', '•', '×', '…' };

    private readonly Texture2D _texture;

    public BitmapFont(Texture2D texture) => _texture = texture;

    // How many screen pixels one font pixel is. Two, which makes a glyph 14 px tall on an 18 px line —
    // about the line the Consolas-15 `SpriteFont` this replaced gave, so a panel keeps its shape. A
    // character is *wider* than that font's, 12 px against roughly 8, which anything that measures its
    // text absorbs (panels size themselves from `Measure`) and anything with a hard-coded width does
    // not. One is at 1:1 for a debug overlay; three is legible at 4K.
    public float PixelSize { get; set; } = 2f;

    // A line of this font is the glyph plus a pixel of air, so stacked lines do not touch.
    public float LineHeight => (GlyphHeight + 2f) * PixelSize;

    // And a character is the glyph plus a pixel of space. Monospaced on purpose: a proportional pixel
    // font at this size is harder to read, and a column of numbers that lines up is worth more than
    // tight kerning.
    //
    // Both are in *screen* pixels, like every other number `UiDraw` lays out with — a metric that
    // forgot `PixelSize` would measure a third of the text it drew.
    public float Advance => (GlyphWidth + 1f) * PixelSize;

    public Vector2 Measure(string text, float scale = 1f)
    {
        if (string.IsNullOrEmpty(text)) return Vector2.Zero;

        int longest = 0, width = 0, lines = 1;
        foreach (char c in text)
        {
            if (c == '\n') { longest = Math.Max(longest, width); width = 0; lines++; continue; }
            width++;
        }
        longest = Math.Max(longest, width);
        return new Vector2(longest * Advance * scale, lines * LineHeight * scale);
    }

    public void Draw(SpriteBatch batch, string text, Vector2 at, Color colour, float scale = 1f) =>
        Draw(batch, text.AsSpan(), at, colour, scale);

    // A slice of a string (a wrapped label's line, #338), without making one.
    internal void Draw(SpriteBatch batch, ReadOnlySpan<char> text, Vector2 at, Color colour, float scale = 1f)
    {
        if (text.IsEmpty) return;

        float x = at.X, y = at.Y;
        float pixel = PixelSize * scale;
        foreach (char c in text)
        {
            if (c == '\n') { x = at.X; y += LineHeight * scale; continue; }

            int index = IndexOf(c);
            if (index >= 0)
            {
                var source = new Rectangle((index % Columns) * Cell, (index / Columns) * Cell,
                                           GlyphWidth, GlyphHeight);
                var destination = new Rectangle((int)MathF.Round(x), (int)MathF.Round(y),
                                                (int)MathF.Round(GlyphWidth * pixel),
                                                (int)MathF.Round(GlyphHeight * pixel));
                batch.Draw(_texture, destination, source, colour);
            }
            x += Advance * scale;
        }
    }

    // Which cell a character is in, or -1 for one the font has never heard of — which draws as a gap
    // rather than throwing, because a missing glyph is a content problem and not a crash (the
    // `DrawString` that threw on an unknown character is exactly what this replaces).
    private static int IndexOf(char c)
    {
        if (c >= FirstCode && c < 127) return c - FirstCode;
        for (int i = 0; i < Extras.Length; i++)
            if (Extras[i] == c) return 127 - FirstCode + i;
        return -1;
    }
}
