#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json.Nodes;

namespace Sage.Simulation;

// The other half of the TrenchBroom bridge (docs/design/15 §3, TODO F16).
//
// An `.fgd` is what tells an editor which entities a game has. Writing one by hand means keeping a
// second list of every prefab, which goes stale the first time somebody adds one — so it is generated
// from the records the game already has, and regenerating it is a console command.
//
// **Every key in here is a key the importer reads.** That rule is worth stating because the temptation
// is the opposite: the engine could reflect over component fields and emit a key for each, and a mapper
// would fill them in and nothing would happen. So a prefab's keys are exactly the ones PrefabKeys
// offers — one per field of each part and component the prefab writes, from the metadata table (issue
// #18) — and MapLoader applies exactly those, through the same PrefabKeys. Each key is typed (integer,
// float, choices for an enum or a flag, color1 for a colour) and described from the field's [Property]:
// its tooltip, unit and range, and the record type a RecordId names.
internal static class FgdExport
{
    public static void RegisterCommand(Engine engine)
    {
        engine.CVars.RegisterCommand("fgd_export", CVarFlags.DevOnly,
            "fgd_export [file]: write a TrenchBroom .fgd for this game's prefabs (default user://sage.fgd).", a =>
        {
            string path = a.Count > 0 ? a[0] : Path.Combine(UserPaths.Root, "sage.fgd");
            try
            {
                File.WriteAllText(path, Build(engine));
                Log.Info(LogCat.Console, $"wrote {path}");
            }
            catch (IOException ex)
            {
                Log.Warn(LogCat.Console, $"fgd_export: {ex.Message}");
            }
        });
    }

    // The file's text. Built as a string rather than written straight out so a test can read it.
    public static string Build(Engine engine, float scale = MapSpace.DefaultScale)
    {
        float unitsPerMetre = scale > 0f ? 1f / scale : 32f;
        var text = new StringBuilder();

        text.AppendLine("// TrenchBroom entity definitions for sage-engine.");
        text.AppendLine("//");
        text.AppendLine("// Generated by `fgd_export` from this game's prefab records — do not edit by hand, it is");
        text.AppendLine("// rewritten whenever the prefabs change. A classname here is a prefab id: what the entity");
        text.AppendLine("// actually is lives in the record, so a game can change it without touching a level.");
        text.AppendLine($"// {unitsPerMetre:0.#} map units to the metre (docs/design/15 §3).");
        text.AppendLine();

        text.AppendLine("@baseclass = Named [");
        text.AppendLine("    targetname(target_source) : \"Name\" : : \"The entity's name in the world, for anything that looks it up.\"");
        text.AppendLine("]");
        text.AppendLine();
        text.AppendLine("@baseclass = Angled [");
        text.AppendLine("    angle(integer) : \"Yaw\" : 0 : \"Degrees counter-clockwise from east, as in Quake.\"");
        text.AppendLine("]");
        text.AppendLine();
        text.AppendLine("@SolidClass = worldspawn : \"The level itself: every brush in it becomes geometry and collision.\" []");
        text.AppendLine();

        // The one point entity that is not a prefab. A mapper who cannot place it from the editor will
        // not place it at all, and it is the marker every level wants; the engine reads it
        // (`MapLevel.TryFindPoint`) and `map_goto` stands the player in it, but nothing spawns here,
        // because where a game starts its player is the game's decision. Its keys are `origin` and
        // `angle`, both of which the importer acts on, which is the rule this file holds to.
        int half = (int)MathF.Round(0.3f * unitsPerMetre);       // a person, roughly: 0.6 m across
        int tall = (int)MathF.Round(1.8f * unitsPerMetre);       // and 1.8 m of them, stood on the mark
        text.AppendLine($"@PointClass base(Angled) size(-{half} -{half} 0, {half} {half} {tall}) = info_player_start : "
                      + "\"Where the player starts. Nothing spawns here: a game reads it off the level, and map_goto stands you in it.\" []");
        text.AppendLine();

        // Entity I/O, as a comment rather than as FGD `output` lines: TrenchBroom is a Quake-family
        // editor and does not parse Source's output syntax, but it does let a mapper type any key on any
        // entity — which is exactly what a wire is. So the file says what to type.
        text.AppendLine("// ---- Wiring (entity I/O, docs/design/04 §3.4) --------------------------------");
        text.AppendLine("//");
        text.AppendLine("// Add a key named after an output, with a value of: target,input[,parameter,delay,times]");
        text.AppendLine("//   \"OnUse\"  \"hut_door,Open\"           using this opens the door named hut_door");
        text.AppendLine("//   \"OnStartTouch\" \"!self,Say,Hello,0,1\"  once, when something walks in");
        text.AppendLine("//");
        text.AppendLine("// Targets may be a targetname, or !self / !activator / !caller.");
        var outputs = new List<string>(engine.Outputs.Names);
        outputs.Sort(StringComparer.OrdinalIgnoreCase);
        text.AppendLine("// Outputs this game fires:");
        foreach (string output in outputs)
            text.AppendLine($"//   {output,-14} {engine.Outputs.Describe(output)}");

        var inputs = new List<string>(engine.Inputs.Names);
        inputs.Sort(StringComparer.OrdinalIgnoreCase);
        text.AppendLine($"// Inputs this game has: {string.Join(", ", inputs)}.");
        text.AppendLine();

        var prefabs = new List<RecordId>(engine.Records.Ids("prefab"));
        prefabs.Sort((a, b) => string.CompareOrdinal(a.ToString(), b.ToString()));

        foreach (var id in prefabs)
        {
            if (!engine.Records.TryGet(id, out PrefabRecord prefab)) continue;

            var (min, max) = SizeOf(engine.Components, id, prefab, unitsPerMetre);
            string description = Describe(id, prefab);

            var keys = PrefabKeys.For(engine, id, prefab);
            if (keys.Count == 0)
            {
                text.AppendLine($"@PointClass base(Named, Angled) size({min}, {max}) = {id.Name} : \"{Escape(description)}\" []");
                continue;
            }
            text.AppendLine($"@PointClass base(Named, Angled) size({min}, {max}) = {id.Name} : \"{Escape(description)}\"");
            text.AppendLine("[");
            foreach (var key in keys) text.AppendLine("    " + Property(key));
            text.AppendLine("]");
        }

        text.AppendLine();
        text.AppendLine($"// {prefabs.Count} prefab(s).");
        // One line ending on every platform (AppendLine writes "\r\n" on Windows): a generated file
        // should come out byte-for-byte the same wherever it is generated, and TrenchBroom reads both.
        return text.ToString().Replace("\r\n", "\n");
    }

    // The box TrenchBroom draws for the entity. A prefab that says how big it is in a `Collider` gets
    // that; anything else gets a small box, because an entity you cannot see is an entity you cannot
    // place. Note the units: the editor thinks in map units and the record is in metres.
    private static (string Min, string Max) SizeOf(ComponentSchema schema, RecordId id, PrefabRecord prefab, float unitsPerMetre)
    {
        float width = 0.5f, height = 1f;

        // A prefab says how big it is in its `body` part far more often than in a `Collider` component,
        // because that is how prefabs are written (`"body": { "size": [0.6, 1.8, 0.6] }` or a capsule's
        // radius and height). Both are read; without the part, every entity in TrenchBroom was the same
        // anonymous cube.
        var collider = ComponentOf(schema, id, prefab, typeof(Collider)) ?? prefab.Parts?["body"] as JsonObject;
        if (collider != null)
        {
            if (collider["size"] is JsonArray size && size.Count >= 3)
            {
                width = Read(size[0], width);
                height = Read(size[1], height);
            }
            else if (collider["radius"] is { } radius)
            {
                width = Read(radius, width) * 2f;
                height = Read(collider["height"], height);
            }
        }

        float halfWidth = width * 0.5f * unitsPerMetre;
        float tall = height * unitsPerMetre;
        var culture = CultureInfo.InvariantCulture;

        // Standing on its feet: the box sits on the entity's origin, which is where a `.map` puts it and
        // where the engine spawns it.
        return ($"{(-halfWidth).ToString("0", culture)} {(-halfWidth).ToString("0", culture)} 0",
                $"{halfWidth.ToString("0", culture)} {halfWidth.ToString("0", culture)} {tall.ToString("0", culture)}");
    }

    // A prefab's fields for one component type, however the prefab spelled its id: `"collider"`,
    // `"sage:collider"` — resolved the way spawning resolves it (ComponentSchema, issue #16).
    private static JsonObject? ComponentOf(ComponentSchema schema, RecordId id, PrefabRecord prefab, Type type)
    {
        if (prefab.Components is null) return null;
        foreach (var (name, fields) in prefab.Components)
            if (schema.TryResolveComponent(name, id.Namespace, out var resolved, out _) && resolved == type)
                return fields as JsonObject;
        return null;
    }

    private static float Read(JsonNode? node, float fallback) =>
        node != null && float.TryParse(node.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out float v)
            ? v : fallback;

    // What the mapper sees in the entity browser: the prefab's own name, and what it is made of — which
    // is the most useful thing the engine can honestly say about it today.
    private static string Describe(RecordId id, PrefabRecord prefab)
    {
        var parts = new List<string>();
        if (prefab.Components != null)
            foreach (var pair in prefab.Components) parts.Add(pair.Key);
        if (prefab.Parts != null)
            foreach (var pair in prefab.Parts) parts.Add(pair.Key);

        string name = string.IsNullOrEmpty(prefab.Name) ? id.Name : prefab.Name;
        return parts.Count == 0 ? $"{name} ({id})" : $"{name} ({id}): {string.Join(", ", parts)}";
    }

    private static string Escape(string text) => text.Replace("\"", "'");

    // One typed, described key: `light.range(float) : "light: Range" : "8" : "Where the light fades
    // to nothing (m, at least 0)"`. The default is what the prefab writes, else the field's own.
    internal static string Property(PrefabKey key)
    {
        var field = key.Field;
        string display = $"{key.Section}: {Human(field.JsonName)}";
        string text = key.DefaultText;
        string description = Escape(DescriptionOf(key));

        switch (field.Kind)
        {
            case ValueKind.Integer:
                return $"{key.Key}(integer) : \"{Escape(display)}\" : {(long.TryParse(text, out long whole) ? whole : 0)} : \"{description}\"";
            case ValueKind.Number:
                return $"{key.Key}(float) : \"{Escape(display)}\" : \"{(text.Length > 0 ? text : "0")}\" : \"{description}\"";
            case ValueKind.Bool:
                return $"{key.Key}(choices) : \"{Escape(display)}\" : {(text == "1" ? 1 : 0)} : \"{description}\" = [ 0 : \"No\" 1 : \"Yes\" ]";
            case ValueKind.Enum:
            {
                string choices = string.Join(" ", field.EnumValues.Select(v => $"\"{v}\" : \"{v}\""));
                string chosen = field.EnumValues.FirstOrDefault(v => string.Equals(v, text, StringComparison.OrdinalIgnoreCase))
                                ?? field.EnumValues.FirstOrDefault() ?? "";
                return $"{key.Key}(choices) : \"{Escape(display)}\" : \"{chosen}\" : \"{description}\" = [ {choices} ]";
            }
            case ValueKind.Vector3 when IsColour(field):
                return $"{key.Key}(color1) : \"{Escape(display)}\" : \"{(text.Length > 0 ? text : "1 1 1")}\" : \"{description}\"";
            default:
                return $"{key.Key}(string) : \"{Escape(display)}\" : \"{Escape(text)}\" : \"{description}\"";
        }
    }

    private static bool IsColour(FieldMetadata field) =>
        field.JsonName.Contains("colour", StringComparison.OrdinalIgnoreCase) || field.JsonName.Contains("color", StringComparison.OrdinalIgnoreCase);

    // The field's tooltip, then what it is: its unit and range, what it names, whose it is.
    private static string DescriptionOf(PrefabKey key)
    {
        var field = key.Field;
        var facts = new List<string>();
        if (field.Unit != null) facts.Add(field.Unit);
        var culture = CultureInfo.InvariantCulture;
        if (field.Min != null && field.Max != null) facts.Add($"{field.Min.Value.ToString(culture)} to {field.Max.Value.ToString(culture)}");
        else if (field.Min != null) facts.Add($"at least {field.Min.Value.ToString(culture)}");
        else if (field.Max != null) facts.Add($"at most {field.Max.Value.ToString(culture)}");
        if (field.Kind is ValueKind.Vector2 or ValueKind.Vector3 && !IsColour(field))
            facts.Add(field.Kind == ValueKind.Vector2 ? "x y" : "x y z");
        if (field.RecordType != null) facts.Add($"{field.RecordType} record id");
        facts.Add($"{(key.IsPart ? "part" : "component")} {key.Section}");

        string tooltip = field.Tooltip ?? Human(field.JsonName);
        return $"{tooltip} ({string.Join(", ", facts)})";
    }

    // "closeAfter" -> "Close after".
    private static string Human(string name)
    {
        var text = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsUpper(c) && text.Length > 0) text.Append(' ').Append(char.ToLowerInvariant(c));
            else text.Append(text.Length == 0 ? char.ToUpperInvariant(c) : c);
        }
        return text.ToString();
    }
}
